store:
  availabilities:
    - German
    - International
  default_locale: de_DE
  localizations:
    - de_DE
    - en_GB
  categories:
    - Administration
  type: extension
  icon: src/Resources/config/plugin.png
  automatic_bugfix_version_compatibility: true
  description:
    de: file:docs/store.md
    en: file:docs/store.en.md
  installation_manual:
    de: file:docs/manual.md
    en: file:docs/manual.en.md
  tags:
    de:
      - Tools
    en:
      - tools
  videos:
    de: []
    en: []
  highlights:
    de:
      - Import Assistent für Plugin spezifische Demo Pakete
    en:
      - Import assistant for Demo packages
  features:
    de:
      - Fontawesome 5 Free - https://fontawesome.com
      - Animate.css - https://daneden.github.io/animate.css
      - Plugin-Interne Übersetzungen
      - Plugin-Relevante Ergänzungen (z.B. CMS Block Bezeichnungen)
      - Nützliche Stylesheet Ergänzungen
      - Einfache Animationen zum ein- und ausblenden des Mauszeigers
      - Zusätzliche Styles für Social-Media Buttons
    en:
      - Fontawesome 5 Free - https://fontawesome.com
      - Animate.css - https://daneden.github.io/animate.css
      - Internal Translations
      - Plugin Additions (e.g. CMS Elements)
      - CSS Additions
      - Scroll animations
      - Additional CSS for Social-Media Buttons
  faq:
    de: []
    en: []
  images:
    - file: docs/images/admin-settings-1.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-2.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-3.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-4.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-5.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-6.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-7.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-8.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-9.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-10.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-11.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-12.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-13.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-14.png
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 0
    - file: docs/images/admin-settings-15.png
      activate:
        de: true
        en: true
      preview:
        de: true
        en: true
      priority: 100

changelog:
  enabled: true

build:
  zip:
    pack:
      excludes:
        paths:
          - docs
          - TODO.md
