<?php declare(strict_types=1);

namespace MoorlFoundation;

use MoorlFoundation\Core\PluginFoundation;
use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\UninstallContext;

class MoorlFoundation extends Plugin
{
    public const FEED_URL = [
        'https://demo-shop.moorleiche.com',
        'http://dev.rh-webdesign.com'
    ];

    public function uninstall(UninstallContext $uninstallContext): void
    {
        parent::uninstall($uninstallContext); // TODO: Change the autogenerated stub

        if ($uninstallContext->keepUserData()) {
            return;
        }

        /* @var $foundation PluginFoundation */
        $foundation = $this->container->get(PluginFoundation::class);
        $foundation->setContext($uninstallContext->getContext());

        $foundation->dropTables([
            'moorl_foundation_article'
        ]);
    }
}