name: Release extension
on:
    workflow_dispatch:
    push:
        branches:
            - '**'
        paths:
            - 'composer.json'
jobs:
    build:
        if: contains(fromJSON(vars.RELEASE_BRANCHES), github.ref_name)
        uses: moorl/github-actions/.github/workflows/release.yml@main
        with:
            extensionName: ${{ github.event.repository.name }}
            publishShopwareStore: ${{ vars.PUBLISH_SHOPWARE_STORE }}
        secrets:
            accountUser: ${{ secrets.ACCOUNT_USER }}
            accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
            ghToken: ${{ secrets.GITHUB_TOKEN }}
