name: Build extension
on:
    workflow_dispatch:
    push:
        branches:
            - 6.6
            - 6.7
        paths:
            - 'composer.json'

jobs:
    check_version:
        runs-on: ubuntu-latest
        outputs:
            version_changed: ${{ steps.ver.outputs.changed }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Compare composer.json version
              id: ver
              run: |
                  old=$(git show HEAD^:composer.json 2>/dev/null | jq -r '.version // empty')
                  new=$(jq -r '.version // empty' composer.json)
                  
                  if [ "$old" != "$new" ]; then
                    echo "changed=true" >> "$GITHUB_OUTPUT"
                  else
                    echo "changed=false" >> "$GITHUB_OUTPUT"
                  fi

    build:
        if: ${{ needs.check_version.outputs.version_changed == 'true' }}
        needs: check_version
        uses: shopware/github-actions/.github/workflows/store-release.yml@main
        with:
            extensionName: ${{ github.event.repository.name }}
        secrets:
            accountUser: ${{ secrets.ACCOUNT_USER }}
            accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
            ghToken: ${{ secrets.GITHUB_TOKEN }}
