name: Build extension
on:
    workflow_dispatch:
    push:
        branches:
            - 6.7

jobs:
    build:
        uses: shopware/github-actions/.github/workflows/store-release.yml@main
        with:
            extensionName: ${{ github.event.repository.name }}
        secrets:
            accountUser: ${{ secrets.ACCOUNT_USER }}
            accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
            ghToken: ${{ secrets.GITHUB_TOKEN }}
