name: Update Store Info
on:
    push:
        branches:
            - '**'
        paths:
            - 'docs/store.md'
            - 'docs/store.en.md'
            - 'docs/manual.md'
            - 'docs/manual.en.md'
            - '.shopware-extension.yml'
    workflow_dispatch:
jobs:
    update-store-info:
        if: github.ref_name == vars.LATEST_BRANCH && vars.PUBLISH_SHOPWARE_STORE == 'true'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install shopware-cli
              uses: shopware/shopware-cli-action@v1
            - name: Build
              shell: bash
              run: shopware-cli account producer extension info push .
              env:
                  SHOPWARE_CLI_ACCOUNT_EMAIL: ${{ secrets.ACCOUNT_USER }}
                  SHOPWARE_CLI_ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
