name: Update main from version branch
on:
    push:
        branches:
            - '**'
jobs:
    update-main:
        if: github.ref_name == vars.LATEST_BRANCH
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Merge into main
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
        
                  git fetch origin main
                  git checkout main
                  git merge --no-ff $GITHUB_REF_NAME -m "Auto-merge $GITHUB_REF_NAME into main"
                  git push origin main
